In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
print(a)

In [4]:
b = np.array([[1.7, 2.2, 3.1], [5.2, 1.2, 4.4]])

In [5]:
print(b)

[[1.7 2.2 3.1]
 [5.2 1.2 4.4]]


In [6]:
# dimension of array
b.ndim

2

In [7]:
# get shape
b.shape

(2, 3)

In [8]:
# type
b.dtype

dtype('float64')

In [9]:
# size
b.itemsize

8

In [10]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

In [11]:
#get a specific element
a[1,5]

13

In [12]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
np.zeros(2)

array([0., 0.])

In [58]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [ ]:
# all zeros matrix
np.zeros((2,3,4,4))

In [ ]:
#any other number 
np.full((2,2), 99)

In [ ]:
#random decimals
np.random.rand(4,2)

In [ ]:
 #random ints
np.random.randint(3,7, size = (2,3))

In [ ]:
#repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

In [ ]:
#copying arrays
a = np.array([1,2,3])
b = a.copy()
b

# Linear Algebra

In [ ]:
a = np.ones((2,3))
b = np.full((3,2), 3)
b

In [ ]:
np.matmul(a,b)

In [ ]:
np.ones(2)

In [ ]:
c = np.ones((2,2))

In [ ]:
np.linalg.det(c)

#### Statistics

In [27]:
stats = np.array([[1,2,3],[4,5,6]])
stats2 = np.array([[7,8,9],[10,11,12]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.min(stats, axis = 1)

array([1, 4])

In [25]:
after = stats.reshape(1,2,3)
print(after)

[[[1 2 3]
  [4 5 6]]]


In [29]:
#vertically stacking vectors
newstats = np.vstack([stats,stats2,stats])
print(newstats)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]]


#### load data into a file

In [53]:
filedata = np.loadtxt('Test.txt', dtype=int, delimiter = ',', usecols=range(10))
print(filedata)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [54]:
filedata[filedata > 11]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [55]:
filedata = filedata.reshape(4,5)
print(filedata)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [56]:
np.any(filedata > 10, axis=0)

array([ True,  True,  True,  True,  True])